### ISSUE TITLE
Einrichtung von verschiedenen virtuellen Raumtypen als Seitentemplates

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-expo#1]
Folgende Typen für virtuelle Räume werden angeboten:

* Foyer (Eingangsbereich, als Zugang zu den Messeständen und Messesälen, aber auch zum Podium)
* Messestand (ein einzelner Messestand eines Präsentators oder eines Sponsors)
* Messesaal (Übersicht / Thematisch zusammengefasste Messestände)
* Podium (Darstellungsform für aktuellen Vortrag oder Diskussionsrunde)
* Kalender oder Themenübersicht (als Eingang zu den Podien)

**Comment by cassandre** [comment]
Ggf. noch ein legereres Setting (Lounge?) für rein soziale Programmpunkte (Get-together, Party...).
Muss aber vielleicht nicht in die erste Ausbaustufe.

**Comment by cassandre** [comment]
Achso, es werden übrigens keine Seiten-Templates, sondern Custom Post Types. So kann man die Messe vom Layout und Inhalt her besser von der Hauptseite trennen.

**Comment by xwolfde** [comment]
Erkläre das.

Ich hatte Gründe dafür, von Seitentemplates zu schreiben.

**Comment by cassandre** [comment]
Mir war so glasklar, dass wir dafür einen CPT brauchen, dass ich das Seitentemplate überlesen habe, sonst hätte ich früher protestiert. ;-)

Eine Messe ist inhaltlich und zeitlich so eindeutig vom restlichen Website getrennt, dass ich das auch in einer getrennten Struktur abbilden würde. Die Anzahl der Seitentemplates im FAU-Theme ist für viele Benutzer schon verwirrend genug. Es ist nicht nötig, für ein Event, das vielleicht einmal im Jahr stattfindet die Liste zu verdoppeln (Templates für Stand, Halle, Lobby, Foyer, Podium...).

Auch die Messe-Seiten würden dann in der normalen Seitenstruktur auftauchen, obwohl sie inhaltlich nichts mit dem laufenden Webauftritt zu tun haben. Beim CPT ist die Messe ganz übersichtlich in einem eigenen Menüpunkt im Backend wegsortiert. Man könnte ggf. auch Leute nur für die Messe-CPTs berechtigen.

Was sind die Gründe für Seitentemplates?
