### ISSUE TITLE
YouTube Einbindung?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-expo#102]
Kann es sein, dass bei der YouTube Einbindung nicht der PLyr verwendet wird, sondern diese direkt über Google erfolgt?

Wenn ja, bitte mal ändern... Google Tracking wollen wir doch nicht.

![grafik](https://user-images.githubusercontent.com/1070669/137754107-9b65ad51-fda6-4c86-a911-3a6ea6be43c8.png)

**Comment by cassandre** [comment]
Nur, wenn das Plugin rrze-video nicht aktiviert ist. Dann nimmt er den Standard-WP-Video-Shortcode.
