### ISSUE TITLE
Titel der Stände lässt sich nicht mehr umbrechen

### ISSUE THREAD

**Issue by mduven** [RRZE-Webteam/rrze-expo#104]
Das ging ja bisher einfach per HTML, wird nun aber scheinbar gefiltert..
![2021-10-22 11_44_58-Window](https://user-images.githubusercontent.com/28564104/138433185-3e96eb87-eb16-421a-ae6e-91705c3d9212.png)

**Comment by cassandre** [comment]
Kann ich leider nicht reproduzieren. Mit welchem Browser tritt das Problem auf?

**Comment by cassandre** [comment]
Bzw. bislang funktionierte es nur mit `<br>`. Ich habe jetzt noch `<br />` ergänzt, damit sollte es jetzt auch korrekt angezeigt werden.
