### ISSUE TITLE
Darstellung Belegung mit grüner Hintergrundfarbe

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-expo#112]
ggf. wäre es besser, wenn bei der Belegung keine grüne Hintergrundfarbe verwendet wird. Dies ist nämlich nicht ganz neutral zur Farbgebung der Website:
![grafik](https://user-images.githubusercontent.com/1070669/155997135-99955d96-b8b5-4f97-b9cf-11c3364c815b.png)

**Comment by cassandre** [comment]
Transferiert nach RRZE-RSVP: https://github.com/RRZE-Webteam/rrze-rsvp/issues/319
