### ISSUE TITLE
🪲 Foyer (FAU-Theme) | Navigationstafeln & Messepanel - Texte sind unterstrichen

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-expo#121]
- [ ] Navigationstexte im Foyer sind auf Wegweisertafeln unterstrichen
- [ ] Auf dem Messe-Panel ist der Text ebenso unterstrichen

Zu sehen auf: https://www.muster-lehrstuhl.wordpress.rrze.fau.de/foyer/foyer-fachmodulvorstellung/
Safari || FAU Theme

![image](https://user-images.githubusercontent.com/58593037/163164783-35ef5f15-0725-4890-a4f9-b19c9695da51.png)

**Comment by cassandre** [comment]
Ahh... und der Nach-Unten-Button auch!

**Comment by lukasniebler** [comment]
Bei der Messehalle die Navigation unter dem Header:

<img width="2223" alt="Bildschirmfoto 2022-04-13 um 12 58 34" src="https://user-images.githubusercontent.com/58593037/163166184-922048a5-a010-4267-8fb4-c273a9d2cc47.png">
<img width="2223" alt="Bildschirmfoto 2022-04-13 um 12 58 37" src="https://user-images.githubusercontent.com/58593037/163166203-23910225-179a-4256-a1d9-e84e4af41652.png">

**Comment by lukasniebler** [comment]
Betrifft auch Navigation auf Messeständen (oben) | Pfeil (unten) | Galerie-Linktext

![Bildschirmfoto-2022-04-13-um-13 10 00](https://user-images.githubusercontent.com/58593037/163168111-f6cb7d90-1a0f-4942-b7be-c26f04c6d136.png)
