### ISSUE TITLE
🪴 Dekorationen erst nach Veröffentlichung an- / abwählbar

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-expo#122]
Getestet im Event-Theme:

## Issue:
Pflanzen und Dekoration kann erst nach der Veröffentlichung des Custom Post Types an- oder abgewählt werden. Zuvor erscheint nur ein Button "de/select all"

## Screenshot:
<img width="1766" alt="Bildschirmfoto 2022-04-13 um 14 49 17" src="https://user-images.githubusercontent.com/58593037/163183527-b5bdd1c8-e874-4e35-b31a-b537fdd0228a.png">

## Live-Seite zum Testen:
https://www.fau-events.wordpress.rrze.fau.de/booth/mikrobiologie/

**Comment by lukasniebler** [comment]
## Identisch mit Logo-Positionswahl
<img width="734" alt="Bildschirmfoto 2022-04-13 um 14 55 31" src="https://user-images.githubusercontent.com/58593037/163184754-ad608393-3222-47f9-b77c-f552b6d545ce.png">

**Comment by cassandre** [comment]
Ja, weil die Auswahl der Dekorationen und die möglichen Logo-Positionen davon abhängen, welche Vorlage gewählt wurde. Und die steht erst nach dem ersten Speichern fest.
