### ISSUE TITLE
📺 Video-Vorschaubilder | YouTube (ggf. Doku)

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-expo#124]
Aktuell habe ich es noch nicht hinbekommen, dass der Messestand das YouTube Vorschaubild anzeigt.
Wenn man auf das leere Video-Element klickt, landet man stattdessen auf der YouTube-Seite.

(Vielleicht setze ich die Links auch falsch?)
Beispiel: https://www.fau-events.wordpress.rrze.fau.de/booth/mikrobiologie/

**Comment by cassandre** [comment]
Ist RRZE-Video aktiviert?
Ansonsten wird aus Datenschutzgründen tatsächlich nur das Icon mit Link angezeigt.

**Comment by lukasniebler** [comment]
War nicht aktiviert. Aber guter Tipp. Ich pack das in die Doku als Hinweis.

**Comment by lukasniebler** [comment]
In Chrome funktioniert es jetzt Prima.

In Safari erscheinen die Videos bei mir außerhalb des Messestands (rechts schwebend). Oder ohne Vorschau. Bin mir gerade noch nicht sicher, woran es liegt. Vielleicht liegt es auch an meinem Safari. Im Safari Entwicklungsmodus hab ich die Erweiterungen deaktiviert.

https://www.fau-events.wordpress.rrze.fau.de/booth/mikrobiologie/
<img width="1207" alt="Bildschirmfoto 2022-04-13 um 15 15 12" src="https://user-images.githubusercontent.com/58593037/163188394-14835ebc-1094-4287-9ba4-3e501a86a890.png">
<img width="1207" alt="Bildschirmfoto 2022-04-13 um 15 19 49" src="https://user-images.githubusercontent.com/58593037/163189210-d02f5b88-6dc3-49b7-8989-35446ca40940.png">

**Comment by lukasniebler** [comment]
Mein Chrome zeigt es inzwischen auch nicht mehr an. (Vorhin hatte es aber mal funktioniert. Vielleicht liegt es am YouTube Link?)

**Comment by lukasniebler** [comment]
Wenn ich das Logo auf Wand / Tisch einblende, werden die Vorschaubilder in Chrome wieder angezeigt

**Comment by lukasniebler** [comment]
In Safari erscheinen Sie wohl mit fixed position immer an der gleichen falschen Stelle. Beim Browser resizen verschieben Sie sich nicht.
<img width="1207" alt="Bildschirmfoto 2022-04-13 um 15 32 01" src="https://user-images.githubusercontent.com/58593037/163191902-12e074fb-3756-42e1-95d0-53ddf8f5b318.png">
<img width="1207" alt="Bildschirmfoto 2022-04-13 um 15 31 55" src="https://user-images.githubusercontent.com/58593037/163191873-31191523-34ef-4167-bd31-d45c5d8264d4.png">

**Comment by lukasniebler** [comment]
Wenn ich im CSS Stylesheet in Safari bei dieser Klasse ein position: relative ergänze:
![Bildschirmfoto 2022-04-13 um 16 50 02](https://user-images.githubusercontent.com/58593037/163208100-df41f10c-d41b-4674-9b96-2916bdaaba19.png)
<img width="2067" alt="Bildschirmfoto 2022-04-13 um 16 51 45" src="https://user-images.githubusercontent.com/58593037/163208287-5ada08f0-3b9c-4a7a-bc74-4b32a0b9963d.png">

Dann wandern in Safari die Vorschaubilder zwar an die falsche Position, aber Sie sind wieder vereint mit den grau/schwarzen Hintergrundboxen?

Vielleicht hilft dir das weiter. Falls ich noch was finde, schreib Ichs hier mit rein

**Comment by lukasniebler** [comment]
<img width="2067" alt="Bildschirmfoto 2022-04-13 um 16 53 10" src="https://user-images.githubusercontent.com/58593037/163208575-ed927819-5d03-4fdd-aeee-0e1732ff5fbe.png">

Aber ich verstehe an der Stelle jetzt auch nicht, wieso im Inspector die Kacheln weiter Rechts angezeigt werden. Vielleicht ein Browser Issue? Habe mich jetzt auch mal durch etliche Elemente durchgeklickt und Css auskommentiert, aber bin nicht dahinter gekommen, weshalb das da rechts fixed schwebt... 

Ich schau morgen nochmal. Schönen Feierabend

**Comment by lukasniebler** [comment]
Weitere Erkenntnisse am Morgen:

wurden erst wieder gar keine Videos angezeigt (Also nur die Play-Icons).
Fix war: Pflanze Rechts einblenden und Stand aktualisieren.

Danach im Browser mit leerem Cache neu laden, dann werden in Firefox / Chrome Thumbnails korrekt angezeigt.
in Safari mit fixed position an der falschen Stelle.

**Comment by lukasniebler** [comment]
Ist glaube ich kein Fehler im expo-Stylesheet.
Selbst wenn das Expo-Stylesheet deaktiviert ist, schweben die Videos unten rechts.

Mit deaktiviertem rrze-video-Stylesheet sieht es so aus:
<img width="2067" alt="Bildschirmfoto 2022-04-14 um 09 17 17" src="https://user-images.githubusercontent.com/58593037/163333946-5a43837b-43a9-4d8c-a8fc-96cde36de794.png">

**Comment by lukasniebler** [comment]
Ab Zeile 84 im Rrze-video.css sorgt schon das erste position: relative dafür, dass die Videos in Safari nach rechts springen, obwohl (zumindest beim durchschauen) keine positionswerte gesetzt wurden...

![Bildschirmfoto 2022-04-14 um 09 24 42](https://user-images.githubusercontent.com/58593037/163335095-3c9791d2-b9d1-40b4-a3df-21260b1099d9.png)
<img width="1655" alt="Bildschirmfoto 2022-04-14 um 09 25 01" src="https://user-images.githubusercontent.com/58593037/163335146-27891500-a4f4-4dc4-ac9e-776e6ef15017.png">

Mit position static, wenn alle anderen Stylesheets gelöscht werden, liegt es dagegen perfekt in Position:
![Bildschirmfoto 2022-04-14 um 09 29 08](https://user-images.githubusercontent.com/58593037/163335824-f5d15784-98f3-4ffc-b431-c05cfc7ce309.png)
<img width="1321" alt="Bildschirmfoto 2022-04-14 um 09 30 05" src="https://user-images.githubusercontent.com/58593037/163335987-7b0e0f63-73f5-4959-890c-9115ca71a377.png">
