### ISSUE TITLE
📺 Videos in der Sidebar benennen

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-expo#129]
Es gab den Wunsch Videos in der Sidebar zu benennen. Aktuell stet dort z.B. "Video 1" oder "Video 2" unter einem Messestand.

Nähere Details im Helpdesk unter 🎫 http://go.fau.de/9svex

**Comment by cassandre** [comment]
https://github.com/RRZE-Webteam/rrze-expo/commit/7e5f6035a7a627eb2f1594e9ce73634a74c426cf
