### ISSUE TITLE
Text auf Infotafel im Foyer

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-expo#134]
Die Fläche der Infotafel im Foyer ist wohl begrenzt, jedenfalls wird bei langem Text ein Teil davon abgeschnitten. Das macht so schon Sinn, aber könnte man einen Infotext über das Eingabefeld setzen? Sowas wie:
"Die Fläche der Infotafel ist begrenzt und damit auch die Textmenge. Prüfen Sie deshalb das Foyer auf mehreren Bildschirmen, um sicherzugehen, dass Ihr Text vollständig angezeigt wird."
Oder gibt es eine bessere Lösung?

![Screenshot 2022-10-27 at 16-40-41 Foyer Wege ins Ausland Friedrich-Alexander-Universität Erlangen-Nürnberg](https://user-images.githubusercontent.com/53909165/198320599-86d5b725-fb5e-4299-9455-f742928806a6.png)

**Comment by cassandre** [comment]
https://github.com/RRZE-Webteam/rrze-expo/commit/104b3a355b576acc89187c0e62c4634543fb5d43
