### ISSUE TITLE
expo-title und expo-subtitle: Zeilenhöhe liegt unter dem Mindestwert, Schriftgröße ist fest

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-expo#139]
Siteimprove mäkelt, dass die Zeilenhöhe bei den beiden Headlines nicht passt und die Schriftgröße fest ist.
Beispiel wäre hier: https://www.fau.de/booth/referat-fuer-internationale-angelegenheiten/
Geht um die Headlines oben: "Wege ins Ausland" und "Möglichkeiten für Auslandsaufenthalte"

**Comment by cassandre** [comment]
https://github.com/RRZE-Webteam/rrze-expo/commit/6268c4fc84fbd9df1f01c4c826cab4e149328e67
