### ISSUE TITLE
Messestände: Überschriften-Hierarchie bei Videos 

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-expo#142]
Wenn bei Messeständen Videos eingebunden werden und der Consent-Banner für YT-Videos abgelehnt wird, steht statt den Videos der typische "Hier könnte ein Video sein"-Text. In so einem Fall ist die Überschrift "Externen Inhalt anzeigen" eine H3 und damit nicht in der passenden Überschriftenhierarchie. Es müsste vermutlich eigentlich mit einer H2 weitergehen. 

Beispiel: https://www.fau.de/booth/fachbereich-wiso/

Kann man das einfach umgehen, indem der Messestand-Name eine H2 wird? Also in dem Beispiel-Fall "Fachbereich WiSo"? Das würde vielleicht auch in anderen Fällen weiterhelfen, wo die Autor*innen unten im Text mit einer H3 starten.

**Comment by cassandre** [comment]
Liegt am Plugin RRZE-Legal, wird dort gefixt.
