### ISSUE TITLE
Erstellung von Basis-SVGs: Messestand

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-expo#19]
Eine SVG-Datei für einen Messestand soll erzeugt werden. Die Inhalte sind in #4 definiert.

Zu beachten ist, dass die Gruppen im SVG bei Nutzung von Photoshop oder einem anderen Vektor-Grafikbearbeitungsprogramm  sauber definiert werden müssen.
Nach dem Export zu SVG ist die SVG Datei ggf. nachzubearbeiten um style="" Angaben zu ergänzen.

**Comment by ej64ojyw** [comment]
Zwei SVG's für Raum 1 und Raum 2 sind erstellt mit den vorläufigen Elementen und Ebenen:

- [x] Palme (Raumpflanze auf rechter Seite)
- [x] Topf (Blumentopf)

- [x] Rollupframe (Rahmen der Rollupfläche)
- [x] Rollupakzent (Rollupfläche mit 50% Opacity)
- [x] Rollupplakat (Rollupfläche mit 100% Opacity)

- [x] Pultplatte (Holzplatte auf dem Pult)
- [x] Pultbasisakzent (Pult mit 50% Opacity zum Einfärben)
- [x] Pultbasis (Pult mit 100% Opacity)

- [x] Prospekthalter (Aufsteller für Grafiken)

- [x] Socialmediapanel (Aufsteller für Social-Media-Icons)

- [x] Wandakzent (50% Opacity zum Einfärben)
- [x] Wand (100% Opacity)

- [ ] bodenmitschatten (Nur vereinzelt in SVG's enthalten)
- [x] boden

( Raum 2 enthält zusätzlich zur kleinen Pultfläche eine Logoflaeche und logoflaecheakzent )

Ausstehend: Optionale Objekte (z.B. zwei Blumentöpfe/Auswahlmöglichkeiten für Pflanzen, FAU-Figur, ein weiteres Roll-Up)
