### ISSUE TITLE
Erstellung von Basis-SVGs: Foyer

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-expo#20]
Eine SVG-Datei für einen Messestand soll erzeugt werden. Die Inhalte sind in #5  definiert.

Zu beachten ist, dass die Gruppen im SVG bei Nutzung von Photoshop oder einem anderen Vektor-Grafikbearbeitungsprogramm  sauber definiert werden müssen.
Nach dem Export zu SVG ist die SVG Datei ggf. nachzubearbeiten um style="" Angaben zu ergänzen.

**Comment by ej64ojyw** [comment]
Die Basis-SVG für das Foyer liegt ab sofort in der FAU Box.
