### ISSUE TITLE
Erstellung von Basis-SVGs: Podium

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-expo#21]
Eine SVG-Datei für einen Messestand soll erzeugt werden. Die Inhalte sind in #6 definiert.

Zu beachten ist, dass die Gruppen im SVG bei Nutzung von Photoshop oder einem anderen Vektor-Grafikbearbeitungsprogramm sauber definiert werden müssen.
Nach dem Export zu SVG ist die SVG Datei ggf. nachzubearbeiten um style="" Angaben zu ergänzen.

**Comment by ej64ojyw** [comment]
Erste Version des Podiums ist jetzt in der FAU Box angelegt. (Podium 1)
Eine alternative Version für das Podium, passend für den Raum 2 folgt.
