### ISSUE TITLE
Einstiegsseite ? 

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-expo#25]
Soll es eine separate Einstiegsseite geben, oder ist das Foyer der Einstieg?

**Comment by xwolfde** [comment]
Ich denke, dass wird man selbst festlegen können, da es ja nur Templates sind.

Sprich: Die Zeile (automatische Verlinkung von z.B. Themenseiten oder Foyer zu Ständen) würde ich abhängig von der Seitenhierarchie machen. Aber wo/was die EInstiegsseite ist, würde ich dem Webmaster frei überlassen.

**Comment by cassandre** [comment]
Ich meine ein Extra Template. Expo-IP hat ja wohl auch eine fancy Willkommensseite mit Außenansicht des Gebäudes, und dann drinnen erst das Foyer.

**Comment by xwolfde** [comment]
hm.. ok, wenn du denkst, das wird gebraucht, dann los

**Comment by cassandre** [comment]
Done.
