### ISSUE TITLE
Bestandteile Template Einstiegsseite

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-expo#26]
(zu definieren)

Ref #25

**Comment by cassandre** [comment]
Wie sinnvoll ist die Adresse bei einem virtuellen Event? Schema.org bietet für Events neuerdings auch VirtualLocation an.

**Comment by xwolfde** [comment]
damit sind ja nur die Kontaktdaten des Ausrichters gemeint...

**Comment by cassandre** [comment]
Ist alles drin, und mit Schema.org/Event ausgezeichnet
