### ISSUE TITLE
Bestandteile Template Messestand

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-expo#4]
Folgende Bestandteile soll ein Messestand aufweisen können.
Diese sind mittels geeignetem SVG darzustellen und zu steuern (vgl. #2 )

- [x] Tisch
- [x] Rollups
- [x] Wand mit Logos oder anderen austauschbaren CI-Elementen
- [x] Hintergrundgrafik
- [x] Social Media Panel
- [x] Videoelemente mit Links zu einem Video, ggf. auch mit Mini-Thumbnail
- [x] Prospektständer, ggf. mit Mini-Thumbnails
- [x] Dekoelemente
    * Stühle
    * FAU-Sitzwürfel (Kartons)
    * Sessel
    * Couch
    * Pflanzen
 - [x] optionaler Programmpunkt- oder Terminhinweis, Kalender
 - [x] Navigationselemente
     * Links zur Lobby, Standübersicht, Podium, ...
 - [x] Avatare
     * Lächelnde Menschen oder Comic-Zeichnungen hinter dem Stand

**Comment by cassandre** [comment]
- Icon Kontaktmöglichkeit (siehe #14)

**Comment by xwolfde** [comment]
Gimmicks sind extra #27
