### ISSUE TITLE
 Bestandteile Template Foyer/Lobby

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-expo#5]
Das Foyer bzw. die Lobby soll folgende Bestandteile im SVG Bild haben:

- [x] Wegweiser
- [x] Programm/Zeitplan 
- [x] Alles was auch ein Stand aufweist #4

**Comment by cassandre** [comment]
Ich würde die Stand-Gimmicks weglassen. Das Foyer sollte eher eine klare Navigation ohne Ablenkung ermöglichen. Ggf. ein Video oder Logo, aber keine Social Media, max. 1 oder 2 Einrichtungen.
