### ISSUE TITLE
Darstellungsfehler Podium Version 2 - Laufende Vorträge

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/rrze-expo#51]
Bei laufenden Vorträgen ist das Videofenster in Version 2 problematisch geschnitten.

Zusätzlich wird die Liste der Vorträge dann nicht mehr dargestellt.

Version 2 problematisch:
![Screenshot 2021-06-22 at 09-39-48 Beispielpodium RRZE WP](https://user-images.githubusercontent.com/58593037/122884095-147b7380-d33e-11eb-9e1f-cce42497ec7a.png)

Podium Version 1 korrekt:
![Screenshot 2021-06-22 at 09-41-24 Beispielpodium RRZE WP](https://user-images.githubusercontent.com/58593037/122884089-12b1b000-d33e-11eb-8956-c514b911aa03.png)

Fehler aufgetreten auf: https://www.wordpress.rrze.fau.de/podium/beispielpodium/

**Comment by cassandre** [comment]
in 750040d erledigt
