### ISSUE TITLE
SVG Siegel - Situationsabhängiger Darstellungsfehler auf dem Shirt von FAU Student 3 in Kombination mit FAU Student 1

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/rrze-expo#52]
Fehler gefunden auf : https://www.wordpress.rrze.fau.de/exposition/messe-der-muster/ 

Die SVG's verursachen in Kombination einen Darstellungsfehler am Siegel.

Steht FAU Student 1 eine Position vor FAU Student 3 bekommt FAU Student 3 einen Darstellungsfehler:
![Screenshot 2021-06-22 at 09-52-45 Messe der Muster RRZE WP](https://user-images.githubusercontent.com/58593037/122885905-c8313300-d33f-11eb-8130-961539656dc7.png)

Steht FAU Student 3 eine Position vor FAU Student 1, dann bekommt FAU Student 1 einen Darstellungsfehler mit der Beschnittmaske des FAU Siegels in der SVG:
![Screenshot 2021-06-22 at 09-52-25 Messe der Muster RRZE WP](https://user-images.githubusercontent.com/58593037/122885991-dbdc9980-d33f-11eb-9092-208f111ae5d1.png)

Bonus-Screenshot: 6-fache Ausführung ohne Darstellungsfehler. (war einfach schön anzusehen)
![Screenshot 2021-06-22 at 09-47-25 Messe der Muster RRZE WP](https://user-images.githubusercontent.com/58593037/122885250-345f6700-d33f-11eb-9857-59eab1af76ec.png)

**Comment by cassandre** [comment]
Ah, OK. Kann sein, dass das Siegel in beiden SVGs die selbe ID hat, und dann die Clip-Anweisungen durcheinander kommen.

**Comment by ej64ojyw** [comment]
Ja. Das war quasi mein eigener Fehler. Da ich die ID's damals nicht mit abgeändert habe.

Illustrator erstellt die ID's bei den Beschnittpfaden immer im gleichen Schema.
Bei FAU Student 1 und 3 müsste das dann #SVGID_2_ sein.

**Comment by ej64ojyw** [comment]
Falls dir das was bringt.
Die gesamte Beschnittgruppe hat die id = "fau_BeschnittgruppeSiegel" bei FAU-Student 3 
und bei FAU-Student-1 hat die gesamte Beschnittgruppe eine id ="FAU_Tasche_Siegel"

Bin mir aber nicht sicher, weil das dann mehr Elemente target, als nur die einzelnen Beschnittgruppen.
Umbenennen ist vllt. die bessere Lösung

**Comment by cassandre** [comment]
In c9ee0e15f3a8cc2a2d82f9a4060982aff98d56aa behoben
