### ISSUE TITLE
Messhalle: Schriftfarbe der Überschrift

### ISSUE THREAD

**Issue by mduven** [RRZE-Webteam/rrze-expo#63]
https://www.strategie.wiso.rw.fau.de/hall/topic-taskforce-area/

Man kann sie im Backend wohl ändern, aber die Änderungen greifen nicht.

**Comment by cassandre** [comment]
Nun ja, gegen ein `h1 {color: #000000 !important;}` im Customizer > Eigenes CSS kommen die Style-Angaben des Plugins  leider nicht an. ;-)
