### ISSUE TITLE
Messe-Startseite wurde nicht dargestellt

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/rrze-expo#74]
Hier war nochmal ein Ticket, dass die Startseite der Messe nicht dargestellt werden kann.
http://go.fau.de/9r-88

(Habe die Permalink-Einstellungen einmal neu gespeichert, danach war Ausgabe problemlos möglich.)

**Comment by cassandre** [comment]
In 0f949081b41bf1495dbcdc540f3baa89944f4260 erledigt.
