### ISSUE TITLE
Titel der Stände ausblendbar machen

### ISSUE THREAD

**Issue by mduven** [RRZE-Webteam/rrze-expo#85]
Gibt es eine Möglichkeit, die Titel auf den Ständen optional (z.B. per Haken) auszublenden? Wir haben immer wieder mal Stände, bei denen das auf den von Firmen geschickten Hintergrundbildern bereits steht, dann ist beides nicht lesbar.
![2021-09-16 10_54_40-](https://user-images.githubusercontent.com/28564104/133582840-10b5d93e-d08a-44ed-9183-220ded0cfc50.png)

**Comment by xwolfde** [comment]
Das wäre nicht so gut:

Der Titel als Pixelbestandteil in dem Hintergrundbild ist halt weder für Google noch für responsible Devices mit kleiner AUflösung noch für Screenreader vorhanden.
Besser wäre es, von den Standanbieter sinnvollere Grafiken zu fordern. Mit dieser Art von Grafiken schaden sie sich selbst.
